### ISSUE TITLE
That uses a moog filter emulation? 

### ISSUE THREAD

**Issue by 01GOD** [copych/AcidBox#6]
Thanks for posting those files! I've been looking for a nice intro to PCM style programming on an MCU. 

That is a moog filter emulation or a diode ladder?

**Comment by copych** [comment]
@01GOD currently default is set to tb303 emulation mostly taken from open303 project. But if you are interested, there're config options in synthvoice.h as I remember to use moog and some other variants, but they may require level tuning.
